### ISSUE TITLE
Optogenetic metadata

### ISSUE THREAD

**Issue by samuelbray32** [LorenFrankLab/trodes_to_nwb#110]
Issue to track planned additions for storing optogenetics information using [this new extension](https://github.com/rly/ndx-optogenetics): 

- [ ] Virus metadata 
- [ ] Injection info
- [ ] Excitation Source
- [ ] Optic fiber device
- [ ] Optic fiber placement
- [ ] Optogenetics

Input Strategies:
- [ ] Device yaml's (Like how we manage probes)
- [ ] New fields in the Yaml generator

**Comment by samuelbray32** [comment]
Input data proposal example:

1. Use device yaml files to reduce user-input variation on entries that should be common across many experiments. Can initially source these from lab members and include in package, with option for users to point to additional files:
- Excitation Source Model (the hardware)
```yaml
ExcitationSourceModel: # excitation source device .yml
    name : Omicron LuxX+ 488-100 Model
    description : Laser for optogenetic stimulation
    manufacturer : Omicron
    illumination_type : laser
    wavelength_range_in_nm : [488.0, 488.0]
```

- Optical Fiber
```yaml
OpticalFiber: # optical fiber .yml
    name : Lambda Model
    description : Lambda fiber (tapered fiber) from Optogenix.
    fiber_name : Lambda
    fiber_model : lambda_b5
    manufacturer : Optogenix
    numerical_aperture : 0.39
    core_diameter_in_um : 200.0
    active_length_in_mm : 2.0
    ferrule_name : cFCF - ∅2.5mm Ceramic Ferrule
    ferrule_diameter_in_mm : 2.5
```

- Optogenetic viruses
```yaml
OptogeneticVirus:
    name : AAV-EF1a-DIO-hChR2(H134R)-EYFP
    construct_name : AAV-EF1a-DIO-hChR2(H134R)-EYFP
    description : Excitatory optogenetic construct for ChR2-EYFP expression
    manufacturer : UNC Vector Core
```

2. Edit the metadata yaml-generator to include these formatted options

```yaml
ExcitationSource:
    name : Omicron LuxX+ 488-100 # This should match an excitationSourceDevice.yml
    description : Laser for optogenetic stimulation
    wavelength_in_nm : 488.0 # wavelength of the laser in THIS session
    power_in_W : 0.077
    intensity_in_W_per_m2 : 1e10

OpticalFiber:
    name : Lambda Model # This should match an opticalFiberDevice.yml

OptogeneticVirusInjection:
    name : "AAV-EF1a-DIO-hChR2(H134R)-EYFP Injection"
    description : "AAV-EF1a-DIO-hChR2(H134R)-EYFP injection into GPe."
    hemisphere : right
    location : GPe
    ap_in_mm : -1.5
    ml_in_mm : 3.2
    dv_in_mm : -6.0
    roll_in_deg : 0.0
    pitch_in_deg : 0.0
    yaw_in_deg : 0.0
    reference : "Bregma at the cortical surface"
    virus: AAV-EF1a-DIO-hChR2(H134R)-EYFP # This should match a virus.yml
    titer_in_vg_per_ml : 1e12
    volume_in_uL : 0.45
```
